version: "3.3"
services:
  a-app:
    image: hashicorp/http-echo:latest
    command: ['-text', "hello world A - Publish local port 5678"]
    expose:
      - 5678
    networks:
      mynet:
        ipv4_address: 172.28.5.2
  b-app:
    image: hashicorp/http-echo:latest
    command: ['-text', "hello world B - Redirect to public 8888"]
    expose:
      - 5678
    networks:
      mynet:
        ipv4_address: 172.28.5.3
  c-app:
    image: hashicorp/http-echo:latest
    command: ['-text', "hello world C - Exposed port 5678 only"]
    expose:
      - 5678
    networks:
      mynet:
        ipv4_address: 172.28.5.4
  webapp:
    image: bula-fiji
    build:
      context: ./
      dockerfile: ./dockerfiles/bula-fiji-node.Dockerfile
    expose:
      - 80
    volumes:
      - ./volumes/bula-fiji-node:/var/www/html
    networks:
      mynet:
        ipv4_address: 172.28.5.5
  proxy-node:
    image: "fims-proxy"
    build:
      context: ./
      dockerfile: dockerfiles/proxy-node.Dockerfile
    ports:
      - 8443:8443
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./volumes/proxy-node/caddy:/etc/caddy
      - ./volumes/proxy-node/log:/var/log/caddy
    networks:
      mynet:
        ipv4_address: 172.28.5.6
    depends_on:
      - webapp
      - c-app
      - b-app
      - a-app
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.5.0/24
